-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 11:30:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coalabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coalabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coalabd` DEFAULT CHARACTER SET utf8 ;
USE `coalabd` ;

-- -----------------------------------------------------
-- Table `coalabd`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coalabd`.`escola` (
  `nome` VARCHAR(60) NOT NULL,
  `media` DOUBLE NOT NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coalabd`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coalabd`.`turma` (
  `nome` VARCHAR(45) NOT NULL,
  `escola_nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`nome`, `escola_nome`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_turma_escola1_idx` (`escola_nome` ASC),
  CONSTRAINT `fk_turma_escola1`
    FOREIGN KEY (`escola_nome`)
    REFERENCES `coalabd`.`escola` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coalabd`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coalabd`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `turma_nome` VARCHAR(45) NOT NULL,
  `turma_escola_nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idaluno`, `turma_nome`, `turma_escola_nome`),
  UNIQUE INDEX `idaluno_UNIQUE` (`idaluno` ASC),
  INDEX `fk_aluno_turma1_idx` (`turma_nome` ASC, `turma_escola_nome` ASC),
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_nome` , `turma_escola_nome`)
    REFERENCES `coalabd`.`turma` (`nome` , `escola_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coalabd`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coalabd`.`notas` (
  `und` INT NOT NULL AUTO_INCREMENT,
  `nota` DOUBLE NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`und`, `aluno_idaluno`),
  UNIQUE INDEX `und_UNIQUE` (`und` ASC),
  INDEX `fk_notas_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_notas_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `coalabd`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
